services:
  web:
    image: okaniyoshiii/zoo-arcadia:latest
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: mysql
    volumes:
      - myapp:/var/lib/mysql
    # Charge les variables d'environement depuis un fichier ".env.local"
    # Ce fichier n'est pas envoyé sur Github permettant de protéger les informations dedans
    env_file:
      - .env.local
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
volumes:
  myapp: