version: "3.7"
services:
  web:
    image: okaniyoshiii/zoo-arcadia:latest
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: mysql
    volumes:
      - myapp:/var/lib/mysql
    environment:
      # MYSQL_ROOT_PASSWORD: db_pwd
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/my_secret
      MYSQL_DATABASE: arcadia_db
    secrets: 
      - my_secret
    
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    secrets: 
      - my_secret
volumes:
  myapp:
secrets:
  my_secret:
    file: ./my_secret.txt