version: "3.7"
services:
  web:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
  db:
    image: mysql
    volumes:
      - myapp:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: db_pwd
      MYSQL_DATABASE: arcadia_db
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=192.168.1.21
      - PMA_PORT=3306
volumes:
  myapp:
